### ISSUE TITLE
[DOC] - Remove mention of twitter

### ISSUE THREAD

**Issue by taciturnaxolotl** [thepurplebubble/template#5]
### What is incorrect in the documentation?

https://github.com/thepurplebubble/template/blob/389969a453786325e6511f875aba5fd406e50198/CONTRIBUTING.md?plain=1#L10C6-L10C6

### What should that text say?

Post about it on social media

**Comment by taciturnaxolotl** [comment]
@theamazing0 want to make a pr for this?

**Comment by theamazing0** [comment]
Fixing in #6
